steps:
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=.
      - --image=gcr.io/$PROJECT_ID/impulse-price-extension
      - --location=northamerica-northeast1
      - --cluster=my-cluster

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'impulse-price-extension'
      - '--image=gcr.io/$PROJECT_ID/impulse-price-extension:$COMMIT_SHA'
      - '--region=northamerica-northeast1'
      - '--set-env-vars'
      - '_EBAY_CLIENT_ID=${_EBAY_CLIENT_ID},_EBAY_CLIENT_SECRET=${_EBAY_CLIENT_SECRET},_EBAY_DEV_ID=${_EBAY_DEV_ID},_EBAY_WEBHOOK_VERIFICATION_TOKEN=${_EBAY_WEBHOOK_VERIFICATION_TOKEN},_EBAY_WEBHOOK_ENDPOINT_URL=${_EBAY_WEBHOOK_ENDPOINT_URL}'
      - '--allow-unauthenticated'
